### ISSUE TITLE
Decide on and add a license in readme and lic file

### ISSUE THREAD

**Issue by adautev** [TimeHeroes-org/HeroesCup#24]
Check whether Pirahna license is needed.

**Comment by MilStancheva** [comment]
Piranha license is MIT - https://github.com/PiranhaCMS/piranha.core/blob/master/LICENSE

**Comment by NenoStefanov** [comment]
Within the manager interface Piranha uses a third party WYSISYG editor for editing formatted HTML content. We should check that the current editor licensing terms matches our application.

**Comment by MilStancheva** [comment]
tinymce editor - https://github.com/tinymce/tinymce/blob/develop/LICENSE.TXT 
"GNU Lesser General Public License v2.1
Primarily used for software libraries, the GNU LGPL requires that derived works be licensed under the same license, but works that only link to it do not fall under this restriction. There are two commonly used versions of the GNU LGPL."

**Comment by MilStancheva** [comment]
Most appropriate but still under discussion is: https://opensource.org/licenses/NPOSL-3.0
We are waiting for approval.
